spring:
  application:
    name: economy
  datasource:
    druid:
      url: jdbc:mysql://43.143.47.137:3306/economy?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1qaz!QAZ
      driver-class-name: com.mysql.cj.jdbc.Driver
      testWhileIdle: true
      validationQuery: select 1
      testOnBorrow: true
      validationInterval: 1000
      timeBetweenEvictionRunsMillis: 3600000
      minEvictableIdleTimeMillis: 18000000
      min-idle: 10
      initial-size: 10
      max-active: 10
      testOnConnect: true
      initSQL: select 1
server:
  port: 1002
mybatis:
  #  mapper-locations: classpath:college/springcloud/order/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true