spring:
  application:
    name: economy
  datasource:
    druid:
      url: jdbc:mysql://43.143.47.137:3306/economy?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1qaz!QAZ
      driver-class-name: com.mysql.cj.jdbc.Driver
      testWhileIdle: true
      validationQuery: select 1
      testOnBorrow: true
      validationInterval: 1000
      timeBetweenEvictionRunsMillis: 3600000
      minEvictableIdleTimeMillis: 18000000
      min-idle: 10
      initial-size: 10
      max-active: 10
      testOnConnect: true
      initSQL: select 1
  thymeleaf:
#    模板变更，立即生效
    cache: false
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
server:
  port: 1002
mybatis:
  #  mapper-locations: classpath:college/springcloud/order/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#canal:
#  server: 124.70.187.145:11111
##  对应canal服务配置的example文件下的实例
#  destination: example

